version: '3.3'
services:
  http_proxy:
    build: ./src
    container_name: http_proxy
    ports:
      - '12345:12345'
    volumes:
      - ./logs:/var/log/erss
    command: /bin/sh -c "/http_proxy/main_run.sh"